language: ruby

branches:
  only:
  - develop
  - master

services:
  - docker

before_install:
  # DOCKER_USERNAME and DOCKER_PASSWORD were manually defined as environment variables in TravisCI settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  # docker build & ship
  - docker build -t inriachile/love-manager:${TRAVIS_BRANCH} .
  - docker push inriachile/love-manager:${TRAVIS_BRANCH}
